formatter: markdown

header-from: .header.md

settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true

sections:
  show:
    - header
    - requirements
    - providers
    - inputs
    - outputs

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: replace
