# openapi2-functions.yaml
swagger: '2.0'
info:
  title: apigw-notification
  description: Terraform Cloud notification workflow
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /:
    post:
      operationId: notifcation-request
      x-google-backend:
        address: ${request_url}
      responses:
        '200':
          description: OK
          schema:
            type: string
        '422':
          description: JSON Schema validation error
          schema:
            type: string
        '500':
          description: Error
          schema:
            type: string
